apiVersion: v1
kind: Service
metadata:
  name: {{ include "scand-manager.fullname" . }}
  labels:
    {{- include "scand-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.firewallInjection.enabled }}
      targetPort:  {{ .Values.firewallInjection.containerPort }}
      {{- else }}
      targetPort:  {{ .Values.service.podPort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "scand-manager.selectorLabels" . | nindent 4 }}
